apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: "{{ .Release.Namespace }}"
  name: evershop
  labels:
    app-type: evershop
    app.kubernetes.io/name: evershop
spec:
  selector:
    matchLabels:
      app-type: evershop
      app.kubernetes.io/name: evershop
  template:
    metadata:
      labels:
        app-type: evershop
        app.kubernetes.io/name: evershop
    spec:
      containers:
        - name: back
          image: "{{ .Values.evershop.image }}"
          resources:
            requests:
              memory: 100Mi
              cpu: 50m
          ports:
            - containerPort: 3000
          env:
            - name: DB_NAME
              value: "{{- coalesce .Values.global.postgresql.auth.database .Values.db.database "default" }}"
            - name: DB_USER
              value: "{{- coalesce .Values.global.postgresql.auth.username .Values.db.username "user" }}"
            - name: DB_PASSWORD
              value: "{{- coalesce .Values.global.postgresql.auth.password .Values.db.password }}"
            - name: DB_PORT
              value: "{{- coalesce .Values.global.postgresql.auth.port .Values.db.port 5432 }}"
            - name: DB_HOST
              value: "{{- coalesce .Values.global.postgresql.auth.host .Values.db.host "release-name-postgresql" }}"

---
apiVersion: v1
kind: Service
metadata:
  name: evershop
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: evershop
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: http
      port: 3000
  selector:
    app.kubernetes.io/name: evershop
    app-type: evershop
