## @section Global parameters
## Please, note that this will override the parameters, including dependencies, configured to use the global value
##
global:
  postgresql:
    auth:
      username: ""
      password: ""
      database: ""
      port: ""
      host: "" 
 
db:
  database: ""
  port: ""
  host: "" 
  username: "" 
  password: "" 